//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jpp.DesignCalculations.Calculations.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jpp.DesignCalculations.Calculations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined moment, shear and axial usage.
        /// </summary>
        internal static string AbstractBar_CombinedUsage_Description {
            get {
                return ResourceManager.GetString("AbstractBar_CombinedUsage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string AbstractBar_CombinedUsage_Group {
            get {
                return ResourceManager.GetString("AbstractBar_CombinedUsage_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage.
        /// </summary>
        internal static string AbstractBar_CombinedUsage_Name {
            get {
                return ResourceManager.GetString("AbstractBar_CombinedUsage_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Section of Section.
        /// </summary>
        internal static string AbstractBar_CrossSection_Description {
            get {
                return ResourceManager.GetString("AbstractBar_CrossSection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Properties.
        /// </summary>
        internal static string AbstractBar_CrossSection_Group {
            get {
                return ResourceManager.GetString("AbstractBar_CrossSection_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross Section.
        /// </summary>
        internal static string AbstractBar_CrossSection_Name {
            get {
                return ResourceManager.GetString("AbstractBar_CrossSection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material of Section.
        /// </summary>
        internal static string AbstractBar_Material_Description {
            get {
                return ResourceManager.GetString("AbstractBar_Material_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Properties.
        /// </summary>
        internal static string AbstractBar_Material_Group {
            get {
                return ResourceManager.GetString("AbstractBar_Material_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        internal static string AbstractBar_Material_Name {
            get {
                return ResourceManager.GetString("AbstractBar_Material_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHBC Foundation Depth 2020.
        /// </summary>
        internal static string NHBC2020FoundationDepth_CalculationName {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_CalculationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHBC Chapter 4.2 - Building Near Trees.
        /// </summary>
        internal static string NHBC2020FoundationDepth_Code {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation fo foundation depths in accordance with NHBC Chapter 4.2 - Building Near Trees.
        /// </summary>
        internal static string NHBC2020FoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of existing ground in metres, with respect to sea level.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingGroundLevel_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingGroundLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingGroundLevel_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingGroundLevel_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing ground level is required.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingGroundLevel_Missing {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingGroundLevel_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Ground Level.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingGroundLevel_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingGroundLevel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required foundation depth in metres due to existing planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Planting Depth.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingPlantingFoundationDepth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum depth in metres as a positive number relative to ground level for existing planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingTreeInfluence_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingTreeInfluence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Influences.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingTreeInfluence_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingTreeInfluence_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Tree Influence.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ExistingTreeInfluence_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ExistingTreeInfluence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required foundation depth in metres.
        /// </summary>
        internal static string NHBC2020FoundationDepth_FoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_FoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        internal static string NHBC2020FoundationDepth_FoundationDepth_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_FoundationDepth_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundation Depth.
        /// </summary>
        internal static string NHBC2020FoundationDepth_FoundationDepth_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_FoundationDepth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required foundation depth in metres due to soil plasticity.
        /// </summary>
        internal static string NHBC2020FoundationDepth_MinimumFoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_MinimumFoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        internal static string NHBC2020FoundationDepth_MinimumFoundationDepth_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_MinimumFoundationDepth_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Foundation Depth.
        /// </summary>
        internal static string NHBC2020FoundationDepth_MinimumFoundationDepth_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_MinimumFoundationDepth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of proposed ground in metres, with respect to sea level.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedGroundLevel_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedGroundLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedGroundLevel_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedGroundLevel_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Ground Level.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedGroundLevel_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedGroundLevel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required foundation depth in metres due to proposed planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedPlantingFoundationDepth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum depth in metres as a positive number relative to ground level for proposed planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedTreeInfluence_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedTreeInfluence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Influences.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedTreeInfluence_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedTreeInfluence_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed Tree Influence.
        /// </summary>
        internal static string NHBC2020FoundationDepth_ProposedTreeInfluence_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_ProposedTreeInfluence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum required foundation depth in metres due to removed planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depths.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedExistingPlantingFoundationDepth_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum depth in metres as a positive number relative to ground level for removed planting.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedTreeInfluence_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedTreeInfluence_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree Influences.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedTreeInfluence_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedTreeInfluence_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Tree Influence.
        /// </summary>
        internal static string NHBC2020FoundationDepth_RemovedTreeInfluence_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_RemovedTreeInfluence_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume change potential based on modified Atterburg limits.
        /// </summary>
        internal static string NHBC2020FoundationDepth_SoilPlasticity_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_SoilPlasticity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Properties.
        /// </summary>
        internal static string NHBC2020FoundationDepth_SoilPlasticity_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_SoilPlasticity_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil Volume Change Potential.
        /// </summary>
        internal static string NHBC2020FoundationDepth_SoilPlasticity_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_SoilPlasticity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level of top of concrete in metres, with respect to sea level.
        /// </summary>
        internal static string NHBC2020FoundationDepth_TopOfConcreteLevel_Description {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_TopOfConcreteLevel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levels.
        /// </summary>
        internal static string NHBC2020FoundationDepth_TopOfConcreteLevel_Group {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_TopOfConcreteLevel_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top of Concrete.
        /// </summary>
        internal static string NHBC2020FoundationDepth_TopOfConcreteLevel_Name {
            get {
                return ResourceManager.GetString("NHBC2020FoundationDepth_TopOfConcreteLevel_Name", resourceCulture);
            }
        }
    }
}
